framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: '%env(MAILER_FROM_EMAIL)%'
        headers:
            From: '%env(MAILER_FROM_NAME)% <%env(MAILER_FROM_EMAIL)%>'

when@dev:
    framework:
        mailer:
            # Pour le développement, utiliser un transport de test
            # dsn: 'null://null'
            # Ou utiliser Mailpit/MailHog pour les tests locaux
            # dsn: 'smtp://127.0.0.1:1025'

when@test:
    framework:
        mailer:
            dsn: 'null://null'